#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

environment:
  matrix:
    - project_name: src/HDInsightManagementCLI/HDInsightManagementCLI.sln

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - echo %project_name%
  - nuget-restore %project_name%

build:
  parallel: true
  project: $(project_name)

  # MSBuild verbosity level
  verbosity: normal

#---------------------------------#
#           artifacts             #
#---------------------------------#

artifacts:
  - path: src\HDInsightManagementCLI\bin
    name: HDInsightManagementCLI.{version}
    type: zip

